version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - FLASK_APP=./flask/run.py
      - FLASK_ENV=development
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  db:
    image: postgres:12-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=tests_db
  # Note: to init database run below after build
  # docker-compose exec flask python manage.py create_db

volumes:
  postgres_data:
